name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Look Changelog
        uses: jaywcjlove/changelog-generator@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (renovate-bot|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - run: npm install
      - run: npm run build
      # 生成文档
      - run: export CI=false && npm run build:website

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          package-path: ./core/package.json

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (renovate-bot|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}
          body: |
            ```bash
            npm i kktp@${{steps.create_tag.outputs.version}}
            npm i @kkt/doc@${{steps.create_tag.outputs.version}}
            npm i @kkt/plugin-pro-config@${{steps.create_tag.outputs.version}}
            npm i @kkt/plugin-pro-entry@${{steps.create_tag.outputs.version}}
            npm i @kkt/plugin-pro-rematch@${{steps.create_tag.outputs.version}}
            npm i @kkt/plugin-pro-router@${{steps.create_tag.outputs.version}}
            npm i @kkt/pro@${{steps.create_tag.outputs.version}}
            npm i @kkt/request@${{steps.create_tag.outputs.version}}
            ```
            ${{ steps.changelog.outputs.compareurl }}
            ${{ steps.changelog.outputs.changelog }}

      - run: mkdir -p website/build/zip

      - name: Compress basic Example.
        run: zip -r -y basic.zip . -x "node_modules/*"  -x "src/.kktp/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json" -x "package-lock.json"
        working-directory: examples/basic
      - run: cp -rp examples/basic/basic.zip  website/build/zip

      - name: Compress access Example.
        run: zip -r -y access.zip . -x "node_modules/*"  -x "src/.kktp/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json" -x "package-lock.json"
        working-directory: examples/access
      - run: cp -rp examples/access/access.zip  website/build/zip  

      - name: Compress rematch Example.
        run: zip -r -y rematch.zip . -x "node_modules/*"  -x "src/.kktp/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json" -x "package-lock.json"
        working-directory: examples/rematch
      - run: cp -rp examples/rematch/rematch.zip  website/build/zip

      - name: Compress auto-routes Example.
        run: zip -r -y auto-routes.zip . -x "node_modules/*"  -x "src/.kktp/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json" -x "package-lock.json"
        working-directory: examples/auto-routes
      - run: cp -rp examples/auto-routes/auto-routes.zip  website/build/zip

      - name: Compress config Example.
        run: zip -r -y config.zip . -x "node_modules/*"  -x "src/.kktp/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json" -x "package-lock.json"
        working-directory: examples/config
      - run: cp -rp examples/config/config.zip  website/build/zip

      - name: Compress mocker Example.
        run: zip -r -y mocker.zip . -x "node_modules/*"  -x "src/.kktp/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json" -x "package-lock.json"
        working-directory: examples/mocker
      - run: cp -rp examples/mocker/mocker.zip  website/build/zip

      - name: Compress routes Example.
        run: zip -r -y routes.zip . -x "node_modules/*"  -x "src/.kktp/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json" -x "package-lock.json"
        working-directory: examples/routes
      - run: cp -rp examples/routes/routes.zip  website/build/zip

      - name: Add Download Page
        working-directory:  website/build/zip
        run: |
          ICON='<svg viewBox="0 0 1024 1024" width="14" height="14"><path d="M192 384h640a42.666667 42.666667 0 0 1 42.666667 42.666667v362.666666a42.666667 42.666667 0 0 1-42.666667 42.666667H192v106.666667a21.333333 21.333333 0 0 0 21.333333 21.333333h725.333334a21.333333 21.333333 0 0 0 21.333333-21.333333V308.821333L949.909333 298.666667h-126.528A98.048 98.048 0 0 1 725.333333 200.618667V72.661333L716.714667 64H213.333333a21.333333 21.333333 0 0 0-21.333333 21.333333v298.666667zM128 832H42.666667a42.666667 42.666667 0 0 1-42.666667-42.666667V426.666667a42.666667 42.666667 0 0 1 42.666667-42.666667h85.333333V85.333333a85.333333 85.333333 0 0 1 85.333333-85.333333h530.026667L1024 282.453333V938.666667a85.333333 85.333333 0 0 1-85.333333 85.333333H213.333333a85.333333 85.333333 0 0 1-85.333333-85.333333v-106.666667z m32.661333-359.509333v38.4h147.072l-158.592 200.448V746.666667h226.176v-38.4H207.893333l158.208-200.064v-35.712h-205.44z m251.136 0V746.666667h44.928V472.490667h-44.928z m98.688 0V746.666667h44.928v-105.216h67.968c66.816 0 100.224-28.416 100.224-84.864 0-56.064-33.408-84.096-99.456-84.096h-113.664z m44.928 38.4h65.28c19.584 0 34.176 3.456 43.392 10.752 9.216 6.912 14.208 18.432 14.208 34.944 0 16.512-4.608 28.416-13.824 35.712-9.216 6.912-23.808 10.752-43.776 10.752h-65.28v-92.16z" fill="currentColor"></path></svg> '
          CodeSandbox='https://codesandbox.io/s/github/kktjs/kkt-pro/tree/main/examples/'
          GITHUBREADME='https://github.com/kktjs/kkt-pro/tree/main/examples/'
          VERSION_NUMBER=$(echo "${{ steps.create_tag.outputs.versionNumber || steps.create_tag.outputs.version || steps.create_tag.outputs.preversion }}")
          cat > index.html << EOF
          <!DOCTYPE html><html lang="en">
          <head>
          <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
          <link rel="icon" type="image/x-icon" href="https://github.githubassets.com/favicon.ico">
          <title>KKTP Example Zip Files</title>
          <style type="text/css">
          body, html { height: 100%; font-size: 12px; font-family: Avenir Next,PingFang SC,Hiragino Sans GB,Droid Sans Fallback,Microsoft YaHei,sans-serif; }
          h1 { font-size: 2.6rem; font-weight: 300; }
          h1 sup { color: #7b7b7b; font-size: 14px; position: absolute; font-weight: normal;}
          a:hover { color: #0949d1; }
          .header { position: relative; width: 100%; height: 60%; text-align: center; }
          .list { border-spacing: 0; border-collapse: collapse; margin: 0 auto 0 auto;}
          .list td { padding: 3px 10px; line-height: 21px; }
          .list td svg { display: block; }
          .list tr:hover { background-color: #f1f1f1; }
          .links { text-align: center; padding: 50px 0 0 0; font-size: 14px; }
          .footer { color: #696969; text-align: center; padding: 10px 0 90px 0; }
          .footer a { padding: 10px 0 90px 0; color: #696969 }
          </style>
          </head>
          <body>
          <table class="header"> <tbody> <tr> <td>
            <h1>KKTP Example Zip Files<sup>v$VERSION_NUMBER</sup></h1>
          </td> </tr> </tbody> </table>
          <table class="list">
            <tbody>
          $(for file in $(ls *.zip); do
            echo "<tr>"
            echo "<td>${ICON}</td>"
            echo "<td><a href=\"${file}\">$file</a></td>"
            echo "<td><a target=\"__blank\" href=\"$GITHUBREADME${file//.zip/}\">Document</a></td>"
            echo "</tr>"
          done)
            </tbody>
          </table>
          <div class="links">
            <a target="__blank" href="https://github.com/kktjs/kkt-pro">GitHub</a> ·
            <a target="__blank" href="https://github.com/kktjs/kkt-pro/issues">Feedback</a> ·
            <a target="__blank" href="https://github.com/kktjs/kkt-pro">Create KKTP Project</a> ·
            <a target="__blank" href="https://github.com/kktjs/kkt-pro">kktp</a>
          </div>
          <div class="footer">
            Licensed under MIT. (Yes it's free and open-sourced)
            <div>
              Created By <a target="__blank" href="https://github.com/jaywcjlove">小弟调调™</a>
            </div>
          </div>
          </body></html>
          EOF

      - name: 📦 kktp publish to NPM
        uses: kktjs/npm-publish@main
        with:
          token: ${{ secrets.NPM_TOKEN }}
          workspaces: |
            packages/doc
            packages/create-kktp
            packages/plugin/*
            packages/request
            core
            
      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        with:
          filter-author: (renovate\[bot\]|actions-user|renovate-bot|dependabot\[bot\])
          output: ./website/build/CONTRIBUTORS.svg
          avatarSize: 42

      # 生成案例网站
      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
