name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Look Changelog
      uses: jaywcjlove/changelog-generator@v1.5.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filter-author: (renovate-bot|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - run: npm install
    - run: npm run build

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.3.5
      with:
        package-path: ./core/package.json

    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@v1.5.4
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filter-author: (renovate-bot|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.create_tag.outputs.version }}
        tag: ${{ steps.create_tag.outputs.version }}
        body: |
          ```bash
          npm i kktp@${{steps.create_tag.outputs.version}}
          npm i @kkt/doc@${{steps.create_tag.outputs.version}}
          npm i @kkt/plugin-pro-config@${{steps.create_tag.outputs.version}}
          npm i @kkt/plugin-pro-entry@${{steps.create_tag.outputs.version}}
          npm i @kkt/plugin-pro-rematch@${{steps.create_tag.outputs.version}}
          npm i @kkt/plugin-pro-router@${{steps.create_tag.outputs.version}}
          ```
          ${{ steps.changelog.outputs.compareurl }}
          ${{ steps.changelog.outputs.changelog }}

    - name: 📦 kktp publish to NPM
      uses: kktjs/npm-publish@main
      with:
        token: ${{ secrets.NPM_TOKEN }}
        workspaces: |
          packages/doc
          packages/plugin/*
          core
